spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/robot_scheduling?serverTimezone=UTC
    username: root
    password: 888888

  #关闭springboot的banner，使界面更清爽
  main:
    banner-mode: off

#开启mp日志，看sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #关闭mybatisplus的banner，使界面更清爽
  global-config:
    banner: false

